export enum ThaicomProcessingStatus {
  CREATED = 'CREATED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ThaicomImageStatus {
  // In Progress States
  QUEUED = 'QUEUED',
  UPLOAD_PENDING = 'UPLOAD_PENDING',
  UPLOAD_COMPLETED = 'UPLOAD_COMPLETED',
  EXTRACTING = 'EXTRACTING',
  EXTRACTED = 'EXTRACTED',
  CONVERTING_COG = 'CONVERTING_COG',
  VALIDATING_PATTERN = 'VALIDATING_PATTERN',
  GENERATING_METADATA = 'GENERATING_METADATA',
  // Completed States
  READY = 'READY',
  // Aborted Statuses
  ABORTED = 'ABORTED',
  // Failed States
  FAILED_UPLOAD = 'FAILED_UPLOAD',
  FAILED_EXTRACT = 'FAILED_EXTRACT',
  FAILED_CONVERT_COG = 'FAILED_CONVERT_COG',
  FAILED_VALIDATE_PATTERN = 'FAILED_VALIDATE_PATTERN',
  FAILED_METADATA = 'FAILED_METADATA',
  // Deleted Status
  DELETED = 'DELETED',
}

export default ThaicomProcessingStatus
